# Generated by Django 5.2.15 on 2026-06-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcarddeck",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
    ]
