# Generated by Django 5.2.14 on 2026-05-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('words', models.IntegerField(default=0)),
                ('provider', models.CharField(choices=[('local', 'Local'), ('youtube', 'YouTube'), ('hls', 'HLS')], max_length=20)),
                ('video', models.URLField(blank=True)),
                ('youtube_id', models.CharField(blank=True, max_length=255)),
                ('hls', models.URLField(blank=True)),
                ('subtitles', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
