# Generated by Django 5.2.14 on 2026-05-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_bunny_video_id_video_duration_video_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='subtitles',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(blank=True, null=True),
        ),
    ]
