# Generated by Django 5.2.14 on 2026-05-28 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('videos', '0004_category_remove_video_category_video_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='users.language'),
        ),
    ]
