# Generated by Django 5.2.15 on 2026-06-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
