# Generated by Django 5.2.15 on 2026-06-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_alter_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('uploading', 'Uploading'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
