# Generated by Django 5.2.15 on 2026-06-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_video_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('uploading', 'Uploading'), ('transcription_pending', 'Transcription Pending'), ('transcribing', 'Transcribing'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=30),
        ),
    ]
