# Generated by Django 5.2.15 on 2026-06-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='learning_goal',
            field=models.CharField(blank=True, choices=[('travel', 'Travel'), ('work', 'Work'), ('study', 'Study'), ('personal', 'Personal')], max_length=20, null=True),
        ),
    ]
