# Generated by Django 5.2.15 on 2026-06-07 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_learning_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language_learning",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learning_users",
                to="users.language",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="language_native",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="native_users",
                to="users.language",
            ),
        ),
    ]
