# Generated by Django 5.2.15 on 2026-06-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile_language_learning_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="translation_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
