# Generated by Django 5.2.14 on 2026-05-24 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0002_video_bunny_video_id_video_duration_video_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtitleSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField()),
                ('start_seconds', models.FloatField()),
                ('end_seconds', models.FloatField()),
                ('text', models.TextField()),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('ipa', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='videos.video')),
            ],
            options={
                'ordering': ['sequence_order'],
                'indexes': [models.Index(fields=['video'], name='subtitles_s_video_i_c2a57b_idx'), models.Index(fields=['sequence_order'], name='subtitles_s_sequenc_255ea7_idx')],
            },
        ),
    ]
