# Generated by Django 5.2.15 on 2026-06-07 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subtitles", "0001_initial"),
        ("users", "0004_language_translation_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubtitleTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translated_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtitle_translations",
                        to="users.language",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="subtitles.subtitlesegment",
                    ),
                ),
            ],
            options={
                "unique_together": {("segment", "language")},
            },
        ),
    ]
