# Generated by Django 5.2.15 on 2026-06-07 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subtitles", "0002_subtitletranslation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subtitlesegment",
            name="translated_text",
        ),
    ]
