# Generated by Django 5.2.14 on 2026-05-24 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subtitles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
                ('normalized_word', models.CharField(db_index=True, max_length=255, unique=True)),
                ('translation', models.CharField(blank=True, max_length=255, null=True)),
                ('ipa', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency_rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='SubtitleWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_word', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_words', to='subtitles.subtitlesegment')),
                ('vocabulary_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle_words', to='vocabulary.vocabularyword')),
            ],
            options={
                'ordering': ['segment', 'position'],
                'unique_together': {('segment', 'position')},
            },
        ),
    ]
