# Generated by Django 5.2.14 on 2026-05-24 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('learned', 'Learned'), ('review', 'Review')], default='new', max_length=20)),
                ('familiarity', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('incorrect_count', models.IntegerField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vocabulary', to=settings.AUTH_USER_MODEL)),
                ('vocabulary_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vocabulary', to='vocabulary.vocabularyword')),
            ],
            options={
                'unique_together': {('user', 'vocabulary_word')},
            },
        ),
    ]
