# Generated by Django 5.2.14 on 2026-05-24 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_uservocabulary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservocabulary',
            name='correct_count',
        ),
        migrations.RemoveField(
            model_name='uservocabulary',
            name='familiarity',
        ),
        migrations.RemoveField(
            model_name='uservocabulary',
            name='incorrect_count',
        ),
        migrations.RemoveField(
            model_name='uservocabulary',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='uservocabulary',
            name='status',
        ),
        migrations.AddField(
            model_name='uservocabulary',
            name='knowledge_level',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Recognizing'), (3, 'Learning'), (4, 'Known'), (5, 'Mastered')], default=1),
        ),
        migrations.AlterField(
            model_name='uservocabulary',
            name='vocabulary_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to='vocabulary.vocabularyword'),
        ),
    ]
