# Generated by Django 5.2.14 on 2026-05-28 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('vocabulary', '0003_remove_uservocabulary_correct_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyword',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_words', to='users.language'),
        ),
        migrations.AlterField(
            model_name='vocabularyword',
            name='normalized_word',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vocabularyword',
            name='word',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='vocabularyword',
            unique_together={('language', 'normalized_word')},
        ),
    ]
