# Generated by Django 5.2.15 on 2026-06-07 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_language_translation_code"),
        ("vocabulary", "0004_vocabularyword_language_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VocabularyTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translation", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocabulary_translations",
                        to="users.language",
                    ),
                ),
                (
                    "vocabulary_word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="vocabulary.vocabularyword",
                    ),
                ),
            ],
            options={
                "unique_together": {("vocabulary_word", "language")},
            },
        ),
    ]
