# Generated by Django 5.2.15 on 2026-06-07 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0005_vocabularytranslation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vocabularyword",
            name="translation",
        ),
    ]
