# Generated by Django 5.2.15 on 2026-06-07 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_language_translation_code"),
        ("vocabulary", "0006_remove_vocabularyword_translation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="uservocabulary",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="uservocabulary",
            name="language",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_vocabulary",
                to="users.language",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="uservocabulary",
            unique_together={("user", "vocabulary_word", "language")},
        ),
    ]
